name: nextcloud_chat
description: Nextcloud chat application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  assets_gen: 1.5.0
  build_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

assets_gen:
  output: gen/assets.dart
  class_name: Assets
  gen_package_path: true
  ignore_resolution: true
  omit_path_levels: 0
  format_dart_code: false
